version: '3.9'

services:
  mariadb:
    image: mariadb:10.9.3
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=lastfm-collector